const clubsActionTypes = {
  CLUB_REQUEST_START: 'CLUB_REQUEST_START',
  CLUB_REQUEST_SUCCESS: 'CLUB_REQUEST_SUCCESS',
  CLUB_REQUEST_FAIL: 'CLUB_REQUEST_FAIL',
  CLUB_FORM_CLEAR: 'CLUB_FORM_CLEAR',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_CLUB_DETAILS:"SET_CLUB_DETAILS",
  CLUBS_DETAILS_POPUP_BOX_ERROR_MESSAGE:"CLUBS_DETAILS_POPUP_BOX_ERROR_MESSAGE",
  UPDATE_PIC_INFO:"UPDATE_PIC_INFO",
  UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS:"UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS",
  DELETE_CLUBS_REQUEST_SUCCESS:"DELETE_CLUBS_REQUEST_SUCCESS",
  CLUBS_DETAILS_REQUEST_SUCCESS:"CLUBS_DETAILS_REQUEST_SUCCESS",
  CLUBS_DETAILS_REQUEST_FAIL:"CLUBS_DETAILS_REQUEST_FAIL",
  CLUBS_DETAILS_REQUEST_START:"CLUBS_DETAILS_REQUEST_START",
  GET_CLUBS_DETAILS_REQUEST_SUCCESS:"GET_CLUBS_DETAILS_REQUEST_SUCCESS",
  GET_CLUBS_DETAILS_REQUEST_FAIL:"GET_CLUBS_DETAILS_REQUEST_FAIL",
  GET_CLUBS_DETAILS_REQUEST_START:"GET_CLUBS_DETAILS_REQUEST_START",
  GET_UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS:"GET_UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS",
  GET_UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS:"GET_UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS",
  GET_CLUB_DETAILS_PAGE_RESET:"GET_CLUB_DETAILS_PAGE_RESET",
  EDIT_USER:"EDIT_USER",
  DELETE_USER:"DELETE_USER",
  DELETE_REQUEST_START:"  DELETE_REQUEST_START",
  DELETE_REQUEST_SUCCESS:"  DELETE_REQUEST_SUCCESS",
  DELETE_REQUEST_FAILURE:"  DELETE_REQUEST_FAILURE"

}
export default clubsActionTypes;

