const ClubsActionTypes = {
  CLUBS_DETAILS_REQUEST_START: "CLUBS_DETAILS_REQUEST_START",
  CLUBS_LOCATION_HISTORY_REQUEST_START: "CLUBS_LOCATION_HISTORY_REQUEST_START",
  CLUBS_DETAILS_REQUEST_SUCCESS: "CLUBS_DETAILS_REQUEST_SUCCESS",
  CLUBS_LOCATION_HISTORY_REQUEST_SUCCESS:
    "CLUBS_LOCATION_HISTORY_REQUEST_SUCCESS",
  CLUBS_LOCATION_HISTORY_CLICK_TO_VIEW_INFO_BOX:
    "CLUBS_LOCATION_HISTORY_CLICK_TO_VIEW_INFO_BOX",
  CLUBS_DETAILS_REQUEST_FAIL: "CLUBS_DETAILS_REQUEST_FAIL",
  CLUBS_HISTORY_LOCATIONS_REQUEST_FAIL: "CLUBS_HISTORY_LOCATIONS_REQUEST_FAIL",
  ADD_CLUBS_DETAILS_REQUEST_SUCCESS: "ADD_CLUBS_DETAILS_REQUEST_SUCCESS",
  DELETE_CLUBS_REQUEST_SUCCESS: "DELETE_CLUBS_REQUEST_SUCCESS",
  UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS: "UPDATE_CLUBS_DETAILS_REQUEST_SUCCESS",
  UPDATE_PIC_INFO: "UPDATE_PIC_INFO",
  SET_CLUBS_DETAILS_GROUP_ID_VAL: "SET_CLUBS_DETAILS_GROUP_ID_VAL",
  CLUBS_DETAILS_PAGE_RESET: "CLUBS_DETAILS_PAGE_RESET",
  CLUBS_DETAILS_POPUP_BOX_ERROR_MESSAGE:
    "CLUBS_DETAILS_POPUP_BOX_ERROR_MESSAGE",
  SET_CLUB_DETAILS: "SET_CLUB_DETAILS",
  PERIMETER_INITIALIZATION: "PERIMETER_INITIALIZATION",
  SET_LOCATION: "SET_LOCATION",
  ONCHANGE_PERIMETER: "ONCHANGE_PERIMETER",
  CLUBS_PAGE_GROUP_ID: "CLUBS_PAGE_GROUP_ID",
  CLUB_SET_NAV_FROM: "CLUB_SET_NAV_FROM",
  SET_ERROR_MSG: "SET_ERROR_MSG",
  SET_CLUB_LOCATION: "SET_CLUB_LOCATION",
  SET_CLUBS_LOCATION_HISTORY_FROM_TO: "SET_CLUBS_LOCATION_HISTORY_FROM_TO",
  UPDATE_CURFEW_TIME_REQUEST_SUCCESS: "UPDATE_CURFEW_TIME_REQUEST_SUCCESS",
};

export default ClubsActionTypes;
