const clubPlayersActionTypes = {
    USER_DETAILS_REQUEST_START:"USER_DETAILS_REQUEST_START",
    USER_DETAILS_REQUEST_SUCCESS:"USER_DETAILS_REQUEST_SUCCESS",
    USER_DETAILS_REQUEST_FAIL:"USER_DETAILS_REQUEST_FAIL",
    SET_USER_DETAILS:"SET_USER_DETAILS",
    //////////////////////////////////////////////
    GET_USERS_DETAILS_REQUEST_START:"GET_USERS_DETAILS_REQUEST_START",
    GET_USERS_DETAILS_REQUEST_SUCCESS:"GET_USERS_DETAILS_REQUEST_SUCCESS",
    GET_USERS_DETAILS_REQUEST_FAIL:"GET_USERS_DETAILS_REQUEST_FAIL",
    GET_USER_DETAILS_PAGE_RESET:"GET_USER_DETAILS_PAGE_RESET",
    /////////////////////////////////////////
    DELETE_REQUEST_SUCCESS:"DELETE_REQUEST_SUCCESS",
    DELETE_REQUEST_START:"DELETE_REQUEST_START",
    DELETE_REQUEST_FAILURE:"DELETE_REQUEST_FAILURE",
    /////////////////////////////////////////////
    UPDATE_CLUBS_REQUEST_START:"UPDATE_CLUBS_REQUEST_START",
    UPDATE_CLUBS_REQUEST_SUCCESS:"UPDATE_CLUBS_REQUEST_SUCCESS",
    UPDATE_CLUBS_REQUEST_FAILURE:"UPDATE_CLUBS_REQUEST_FAILURE",
    //////////////////////////////////////////////////////
    GET_USERS_REQUEST_START:"GET_USERS_REQUEST_START",
    GET_USERS_DELTAILS:"GET_USERS_DELTAILS",
    GET_USERS_REQUEST_FAILURE:"GET_USERS_REQUEST_FAILURE",
    GET_UPDATE_USERS_DETAILS_REQUEST_SUCCESS:"GET_UPDATE_USERS_DETAILS_REQUEST_SUCCESS"
  }
  export default clubPlayersActionTypes;
