<<<<<<< HEAD
const LoginActionTypes = {
    ON_LOGIN_REQUEST_START: 'ON_LOGIN_REQUEST_START',
    ON_LOGIN_REQUEST_SUCCESS: 'ON_LOGIN_REQUEST_SUCCESS',
    ON_LOGIN_REQUEST_FAIL: 'ON_LOGIN_REQUEST_FAIL',
    ON_LOGIN_FORM_CLEAR: 'ON_LOGIN_FORM_CLEAR',
    USER_LOGIN_REQUEST_START: 'USER_LOGIN_REQUEST_START',
    USER_LOGIN_REQUEST_SUCCESS: 'USER_LOGIN_REQUEST_SUCCESS',
    USER_LOGIN_REQUEST_FAIL: 'USER_LOGIN_REQUEST_FAIL',
    SET_USER_INFO: 'SET_USER_INFO',
    RESET_POPUP_ERROR_MSG: 'RESET_POPUP_ERROR_MSG',
    SET_LOGIN_DETAILS: 'SET_LOGIN_DETAILS',
    RESET_PASSWORD_FAIL:'RESET_PASSWORD_FAIL',
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS'
};

=======
const LoginActionTypes = {
    ON_LOGIN_REQUEST_START: 'ON_LOGIN_REQUEST_START',
    ON_LOGIN_REQUEST_SUCCESS: 'ON_LOGIN_REQUEST_SUCCESS',
    ON_LOGIN_REQUEST_FAIL: 'ON_LOGIN_REQUEST_FAIL',
    ON_LOGIN_FORM_CLEAR: 'ON_LOGIN_FORM_CLEAR',
    SET_USER_INFO: 'SET_USER_INFO',
    RESET_POPUP_ERROR_MSG: 'RESET_POPUP_ERROR_MSG',
    SET_LOGIN_DETAILS: 'SET_LOGIN_DETAILS',
    RESET_PASSWORD_FAIL:'RESET_PASSWORD_FAIL',
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS'
};

>>>>>>> 03ffa5a12daf10079fd3ff5076f21db4c34fe44e
export default LoginActionTypes;