const ValidationActionTypes = {
  VALIDATION_REQUEST_START: "VALIDATION_REQUEST_START",
  VALIDATION_REQUEST_SUCCESS: "VALIDATION_REQUEST_SUCCESS",
  VALIDATION_REQUEST_FAIL: "VALIDATION_REQUEST_FAIL",
  VALIDATION_EXISTING_PHONE: "VALIDATION_EXISTING_PHONE",
  VALIDATION_EXISTING_EMAIL: "VALIDATION_EXISTING_EMAIL",
  SET_VALIDATION_EMAIL_DATA: "SET_VALIDATION_EMAIL_DATA",
  SET_VALIDATION_BRACELET_DATA: "SET_VALIDATION_BRACELET_DATA",
  SET_VALIDATION_PHONE_DATA: "SET_VALIDATION_PHONE_DATA",
  RESET_VALIDATION_DATA: "RESET_VALIDATION_DATA",
  VALIDATION_BRACELET_SUCCESS: "VALIDATION_BRACELET_SUCCESS",
  VALIDATION_VICTIM_REQUEST_SUCCESS: "VALIDATION_VICTIM_REQUEST_SUCCESS",
};

export default ValidationActionTypes;
