const ValidationActionTypes = {
  VALIDATION_REQUEST_START: "VALIDATION_REQUEST_START",
  VALIDATION_REQUEST_SUCCESS: "VALIDATION_REQUEST_SUCCESS",
  VALIDATION_REQUEST_FAIL: "VALIDATION_REQUEST_FAIL",
  RESET_VALIDATION_DATA: "RESET_VALIDATION_DATA",
};

export default ValidationActionTypes;

