<<<<<<< HEAD
import React, { Component } from "react";
import Footer from "../commons/Footer";
import Header from "../commons/Header";

export class Error extends Component {
  render() {
    return (
      <div>
        <h1>
          {`Sorry.... 
                    Try-again After Some-time`}
        </h1>
        <Footer />
      </div>
    );
  }
}

export default Error;
=======
import React, { Component } from "react";
import Footer from "../commons/Footer";
import Header from "../commons/Header";

export class Error extends Component {
  render() {
    return (
      <div>
        <h1>
          {`Sorry.... 
                    Try-again After Some-time`}
        </h1>
        <Footer />
      </div>
    );
  }
}

export default Error;
/* const SupervisorActionTypes = {
    SUPERVISORS_REQUEST_START: 'SUPERVISORS_REQUEST_START',
    SUPERVISORS_REQUEST_SUCCESS: 'SUPERVISORS_REQUEST_SUCCESS',
    SUPERVISORS_REQUEST_FAIL: 'SUPERVISORS_REQUEST_FAIL',
    ADD_SUPERVISORS_REQUEST_SUCCESS: 'ADD_SUPERVISORS_REQUEST_SUCCESS',
    SET_SUPERVISORS_ALPHABET_VAL: 'SET_SUPERVISORS_ALPHABET_VAL',
    SET_SUPERVISORS_GROUP_ID_VAL: 'SET_SUPERVISORS_GROUP_ID_VAL',
    SUPERVISORS_PAGE_RESET: 'SUPERVISORS_PAGE_RESET',

    SUPERVISORS_POPUP_BOX_ERROR_MESSAGE: 'SUPERVISORS_POPUP_BOX_ERROR_MESSAGE',
};

export default SupervisorActionTypes; */
/* const SupervisorDetailsActionTypes = {
    SUPERVISOR_DETAILS_REQUEST_START: 'SUPERVISOR_DETAILS_REQUEST_START',
    SUPERVISOR_DETAILS_REQUEST_SUCCESS: 'SUPERVISOR_DETAILS_REQUEST_SUCCESS',
    SUPERVISOR_DETAILS_REQUEST_FAIL: 'SUPERVISOR_DETAILS_REQUEST_FAIL',
    ADD_SUPERVISOR_DETAILS_REQUEST_SUCCESS: 'ADD_SUPERVISOR_DETAILS_REQUEST_SUCCESS',
    DELETE_SUPERVISOR_REQUEST_SUCCESS: 'DELETE_SUPERVISOR_REQUEST_SUCCESS',
    UPDATE_SUPERVISOR_DETAILS_REQUEST_SUCCESS: 'UPDATE_SUPERVISOR_DETAILS_REQUEST_SUCCESS',
    SET_SUPERVISOR_DETAILS_GROUP_ID_VAL: 'SET_SUPERVISOR_DETAILS_GROUP_ID_VAL',
    SUPERVISOR_DETAILS_PAGE_RESET: 'SUPERVISOR_DETAILS_PAGE_RESET',
    SUPERVISOR_DETAILS_POPUP_BOX_ERROR_MESSAGE: 'SUPERVISOR_DETAILS_POPUP_BOX_ERROR_MESSAGE',
    SET_SUPERVISOR_DETAILS: 'SET_SUPERVISOR_DETAILS',
    VALIDATE_SUPERVISOR_DETAILS: 'VALIDATE_SUPERVISOR_DETAILS',
    SUPERVISOR_PAGE_GROUP_ID: 'SUPERVISOR_PAGE_GROUP_ID',
    SUPERVISOR_SET_NAV_FROM: 'SUPERVISOR_SET_NAV_FROM',
    DELETE_SUPERVISOR_INFO_MSG: 'DELETE_SUPERVISOR_INFO_MSG',
    UPDATE_SUPERVISOR_PIC_INFO: 'UPDATE_SUPERVISOR_PIC_INFO',
    RE_ASSIGN_SUPERVISOR: 'RE_ASSIGN_SUPERVISOR',
    RE_ASSIGN_SUPERVISOR_SUCCESS: 'RE_ASSIGN_SUPERVISOR_SUCCESS',
};

export default SupervisorDetailsActionTypes; */
>>>>>>> 03ffa5a12daf10079fd3ff5076f21db4c34fe44e
